# check swagger documentation here: https://swagger.io/docs/specification/2-0/what-is-swagger/
# Strongly suggested installing Jetbrains "Swagger" plugin

swagger: "2.0"
info:
  title: Emergency Social Network
  description: This network is intended to use as a social connecting tool in case of emergency.
  version: 1.0.4-I4-JimmyWang
basePath: /api
schemes:
  - http
paths:
  /requestPosts:
    get:
      tags:
        - "requestPosts"
      summary: Get all request posts matching the filter
      parameters:
        - in: body
          name: isRequest
          required: true
          schema:
            type: string
            example: 0
            description: |
              Looking for resource supplies (0) or a resource requests(1)
        - in: body
          name: category
          schema:
            type: string
            example: 1
            description: |
              List only the category of the resource provided.
              Limited to "Food&Water"(1), "FirstAid"(2), "Tools&Equipment"(3).
        - in: body
          name: time
          schema:
            type: string
            example: 1
            description: |
              List only the posts within some time range. Provided options are
              (1) within 1 hour
              (2) within 4 hours
              (3) within 1 day
              (4) within 3 days
        - in: body
          name: location
          schema:
            type: string
            example: 94043
            description:
              List only the posts at some zip code.
      produces:
        - application/json
      responses:
        200:
          description: Find all request posts matching the condition.
          schema:
            type: array
            items:
              $ref: '#/definitions/RPSimpleVO'
        500:
          description: Server Error.
    post:
      tags:
        - "requestPosts"
      summary: Create a new resource post
      parameters:
        - in: body
          name: form
          schema:
            $ref: '#/definitions/PostFormVO'
      responses:
        201:
          description: New resource post created.
        400:
          description: The form does not match the VO restrictions.
        500:
          description: Server Error.
  /requestPosts/mine:
    get:
      tags:
        - "requestPosts"
      summary: Get all request posts matching the filter that belongs to the logged in citizen
      parameters:
        - in: body
          name: category
          schema:
            type: string
            description: |
              List only the category of the resource provided.
              Limited to "Food&Water"(1), "FirstAid"(2), "Tools&Equipment"(3).
        - in: body
          name: time
          schema:
            type: string
            description: |
              List only the posts within some time range. Provided options are
              (1) within 1 hour
              (2) within 4 hours
              (3) within 1 day
              (4) within 3 days
        - in: body
          name: location
          schema:
            type: string
            description: |
              List only the posts at some zip code.
      produces:
        - application/json
      responses:
        200:
          description: Find all request posts matching the condition.
          schema:
            type: array
            items:
              $ref: '#/definitions/RPSimpleVO'
        500:
          description: Server Error.
  /requestPosts/{postId}:
    get:
      tags:
        - "requestPosts"
      summary: Get a request post information
      parameters:
        - in: path
          name: postId
          type: string
          required: true
          description: hexadecimal ID of the request post.
      produces:
        - application/json
      responses:
        200:
          description: The Request Post is found.
          schema:
            $ref: '#/definitions/RequestPostVO'
        404:
          description: The request post is not found.
        500:
          description: Server Error.
    put:
      tags:
        - "requestPosts"
      summary: Update a request post
      parameters:
        - in: path
          name: postId
          type: string
          required: true
          description: hexadecimal ID of the request post.
        - in: body
          name: form
          required: true
          schema:
            $ref: '#/definitions/PostFormVO'
      produces:
        - text/plain
      responses:
        200:
          description: The request is successfully updated.
        400:
          description: The form does not match the VO restrictions.
        404:
          description: The post with corresponding postId is not found.
        500:
          description: Server Error.
  /requestPosts/search:
    get:
      tags:
        - "requestPostsSearch"
      summary: Search a list of resource posts that has the keyword in title / remarks
      parameters:
        - in: body
          name: keyword
          schema:
            type: string
            description: |
              The keyword string, contains one or more keywords separated by spaces.
      responses:
        200:
          description: The search is successful and a list of resource posts is returned.
          schema:
            type: array
            items:
              $ref: '#/definitions/RPSimpleVO'
        400:
          description: Bad query string.
        500:
          description: Server Error.


definitions:
  RequestPostVO:
    type: object
    description: A full request post object used in RequestPost Use Case.
    required:
      - id
      - title
      - category
      - postType
      - active
      - quantity
      - zipcode
      - contact
      - timestamp
    properties:
      id:
        type: string
      title:
        type: string
      category:
        type: integer
        minimum: 1
        maximum: 3
        description: |
          Describes the category of the resource provided.
          Limited to "Food&Water"(1), "FirstAid"(2), "Tools&Equipment"(3).
      postType:
        type: boolean
        description: |
          Indicates whether this post is requesting some supply.
          If this field is false, it is providing some supply.
      active:
        type: boolean
        description: |
          Indicates whether the post is active.
          If this field is false, it indicates the post is inactive (outdated).
      quantity:
        type: integer
        description: |
          Describe the quantity of the resource provided / requested.
      zipcode:
        type: integer
        description: |
          A 5-digit US zip code indicating the geological location of the resource provided / requested.
      remarks:
        type: string
        description: |
          Any remark information that the sender wants to add to this post.
      contact:
        type: string
        description: |
          The user ID of the person who sends the post.'
      timestamp:
        type: string
        description: |
          The time when the post is updated.
  PostFormVO:
    type: object
    description: A form schema used when posting / updating a request post.
    required:
      - title
      - category
      - postType
      - active
      - quantity
      - zipcode
    properties:
      title:
        type: string
      category:
        type: integer
        minimum: 1
        maximum: 3
        description: |
          Describes the category of the resource provided.
          Limited to "Food&Water"(1), "FirstAid"(2), "Tools&Equipment"(3).
      postType:
        type: boolean
        description: |
          Indicates whether this post is requesting some supply.
          If this field is false, it is providing some supply.
      active:
        type: boolean
        description: |
          Indicates whether the post is active.
          If this field is false, it indicates the post is inactive (outdated).
      quantity:
        type: integer
        description: |
          Describe the quantity of the resource provided / requested.
      zipcode:
        type: integer
        description: |
          A 5-digit US zip code indicating the geological location of the resource provided / requested.
      remarks:
        type: string
        description: |
          Any remark information that the sender wants to add to this post.
  RPSimpleVO:
    type: object
    description: |
      A simple request post object used in RequestPost Use Case.
      This object is a simplified schema used when listing all posts.
    required:
      - id
      - title
      - category
      - postType
      - active
      - quantity
      - zipcode
      - timestamp
    properties:
      id:
        type: string
      title:
        type: string
      category:
        type: integer
        minimum: 1
        maximum: 3
        description: |
          Describes the category of the resource provided.
          Limited to "Food&Water"(1), "FirstAid"(2), "Tools&Equipment"(3).
      postType:
        type: boolean
        description: |
          Indicates whether this post is requesting some supply.
          If this field is false, it is providing some supply.
      active:
        type: boolean
        description: |
          Indicates whether the post is active.
          If this field is false, it indicates the post is inactive (outdated).
      quantity:
        type: integer
        description: |
          Describe the quantity of the resource provided / requested.
      zipcode:
        type: integer
        description: |
          A 5-digit US zip code indicating the geological location of the resource provided / requested.
      timestamp:
        type: string
        description: |
          The time when the post is updated.
