# check swagger documentation here: https://swagger.io/docs/specification/2-0/what-is-swagger/
# Strongly suggested installing Jetbrains "Swagger" plugin

swagger: "2.0"
info:
  title: Emergency Social Network
  description: |
    This network is intended to use as a social connecting tool in case of emergency.
    This document only contains the APIs for Jimmy Wang's Iteration 4 features.
  version: 1.0.4-I4-JimmyWang
basePath: /api
schemes:
  - http
paths:
  /resourcePosts:
    get:
      tags:
        - "resourcePosts"
      summary: Get all resource posts matching the filter
      parameters:
        - in: body
          description: filter parameters
          name: filter
          schema:
            $ref: '#/definitions/ResourcePostFilter'
      produces:
        - application/json
      responses:
        200:
          description: Find all resource posts matching the condition.
          schema:
            type: array
            items:
              $ref: '#/definitions/RPSimpleVO'
        400:
          description: Invalid Filter Paramters.
        500:
          description: Server Error.
    post:
      tags:
        - "resourcePosts"
      summary: Create a new resource post
      parameters:
        - in: body
          name: form
          schema:
            $ref: '#/definitions/PostFormVO'
      responses:
        201:
          description: New resource post created.
        400:
          description: The form does not match the VO restrictions.
        500:
          description: Server Error.
  /resourcePosts/{postId}:
    get:
      tags:
        - "resourcePosts"
      summary: Get a resource post information
      parameters:
        - in: path
          name: postId
          type: string
          required: true
          description: hexadecimal ID of the resource  post.
      produces:
        - application/json
      responses:
        200:
          description: The resource post is found.
          schema:
            $ref: '#/definitions/ResourcePostVO'
        404:
          description: The resource post is not found.
        500:
          description: Server Error.
    put:
      tags:
        - "resourcePosts"
      summary: Update a resource post (Can only execute if it belongs to the logged in user)
      parameters:
        - in: path
          name: postId
          type: string
          required: true
          description: hexadecimal ID of the resource post.
        - in: body
          name: form
          required: true
          schema:
            $ref: '#/definitions/PostFormVO'
      produces:
        - text/plain
      responses:
        200:
          description: The resource is successfully updated.
        400:
          description: The form does not match the VO restrictions.
        403:
          description: The user is not authorized to update the post. (Only the owner can update it)
        404:
          description: The resource post with the corresponding id is not found.
        500:
          description: Server Error.
    delete:
      tags:
        - "resourcePosts"
      summary: Delete a resource post (Can only execute if it belongs to the logged in user)
      parameters:
        - in: path
          name: postId
          type: string
          required: true
          description: hexadecimal ID of the resource post.
      produces:
        - text/plain
      responses:
        200:
          description: The resource is successfully deleted.
        403:
          description: The user is not authorized to delete the post.
        404:
          description: The resource post with the corresponding id is not found.
        500:
          description: Server Error.
  /resourcePosts/search:
    get:
      tags:
        - "resourcePostsSearch"
      summary: Search a list of resource posts that has the keyword in title / remarks
      parameters:
        - in: body
          name: keyword
          schema:
            type: string
            description: |
              The keyword string, contains one or more keywords separated by spaces.
      responses:
        200:
          description: The search is successful and a list of resource posts is returned.
          schema:
            type: array
            items:
              $ref: '#/definitions/RPSimpleVO'
        400:
          description: Bad query string.
        500:
          description: Server Error.


definitions:
  ResourcePostFilter:
    description: Filter Parameters for GET /researchPost
    properties:
      isRequest:
        type: string
        example: 0
        description: |
            Looking for resource supplies (0) or a resource requests(1)
      category:
        type: string
        example: 1
        description: |
          List only the category of the resource provided.
          Limited to "Food&Water"(1), "FirstAid"(2), "Tools&Equipment"(3).
      time:
        type: string
        example: 1
        description: |
          List only the posts within some time range. Provided options are
          (1) within 1 hour
          (2) within 4 hours
          (3) within 1 day
          (4) within 3 days
      location:
        type: string
        example: 94043
        description: |
          List only the posts at some zip code.
      isMine:
        type: string
        example: 0
        description: |
          Any value will result in the search filters only my posts (with inactive ones).
  ResourcePostVO:
    type: object
    description: A full resource post object used in ResourcePost Use Case.
    required:
      - id
      - title
      - category
      - postType
      - active
      - quantity
      - zipcode
      - contact
      - timestamp
    properties:
      id:
        type: string
      title:
        type: string
      category:
        type: integer
        minimum: 1
        maximum: 3
        description: |
          Describes the category of the resource provided.
          Limited to "Food&Water"(1), "FirstAid"(2), "Tools&Equipment"(3).
      postType:
        type: boolean
        description: |
          Indicates whether this post is requesting some supply.
          If this field is false, it is providing some supply.
      active:
        type: boolean
        description: |
          Indicates whether the post is active.
          If this field is false, it indicates the post is inactive (outdated).
      quantity:
        type: integer
        description: |
          Describe the quantity of the resource provided / requested.
      zipcode:
        type: integer
        description: |
          A 5-digit US zip code indicating the geological location of the resource provided / requested.
      remarks:
        type: string
        description: |
          Any remark information that the sender wants to add to this post.
      contact:
        type: string
        description: |
          The user ID of the person who sends the post.'
      timestamp:
        type: string
        description: |
          The time when the post is updated.
  PostFormVO:
    type: object
    description: A form schema used when posting / updating a resource post.
    required:
      - title
      - category
      - postType
      - active
      - quantity
      - zipcode
    properties:
      title:
        type: string
      category:
        type: integer
        minimum: 1
        maximum: 3
        description: |
          Describes the category of the resource provided.
          Limited to "Food&Water"(1), "FirstAid"(2), "Tools&Equipment"(3).
      postType:
        type: boolean
        description: |
          Indicates whether this post is requesting some supply.
          If this field is false, it is providing some supply.
      active:
        type: boolean
        description: |
          Indicates whether the post is active.
          If this field is false, it indicates the post is inactive (outdated).
      quantity:
        type: integer
        description: |
          Describe the quantity of the resource provided / requested.
      zipcode:
        type: integer
        description: |
          A 5-digit US zip code indicating the geological location of the resource provided / requested.
      remarks:
        type: string
        description: |
          Any remark information that the sender wants to add to this post.
  RPSimpleVO:
    type: object
    description: |
      A simple resource post object used in ResourcePost Use Case.
      This object is a simplified schema used when listing all posts.
    required:
      - id
      - title
      - category
      - postType
      - active
      - quantity
      - zipcode
      - timestamp
    properties:
      id:
        type: string
      title:
        type: string
      category:
        type: integer
        minimum: 1
        maximum: 3
        description: |
          Describes the category of the resource provided.
          Limited to "Food&Water"(1), "FirstAid"(2), "Tools&Equipment"(3).
      postType:
        type: boolean
        description: |
          Indicates whether this post is requesting some supply.
          If this field is false, it is providing some supply.
      active:
        type: boolean
        description: |
          Indicates whether the post is active.
          If this field is false, it indicates the post is inactive (outdated).
      quantity:
        type: integer
        description: |
          Describe the quantity of the resource provided / requested.
      unit:
        type: string
        description: |
          The unit of that quantity.
      zipcode:
        type: integer
        description: |
          A 5-digit US zip code indicating the geological location of the resource provided / requested.
      timestamp:
        type: string
        description: |
          The time when the post is updated.
